DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questionsInfo;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (email)
);

CREATE TABLE sessions (
  id TEXT NOT NULL,
  userId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE events (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE roles (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE permissions (
  userId TEXT NOT NULL,
  eventId TEXT NOT NULL,
  roleId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId, eventId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE languages (
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  eventId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (code),
  FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE teams (
  id TEXT NOT NULL,
  number INTEGER NOT NULL,
  name TEXT NOT NULL,
  eventId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE,
  UNIQUE (eventId, name)
);

CREATE TABLE questions (
  id TEXT NOT NULL,
  -- PS = Points Specific, PW = Points per Word, TF = True/False, FB = Fill in the Blank
  type TEXT NOT NULL CHECK (type IN ('PS', 'PW', 'TF', 'FB')),
  maxPoints NUMERIC NOT NULL,
  seconds NUMERIC NOT NULL,
  eventId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (eventId) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE questionsInfo (
  id TEXT NOT NULL,
  body TEXT NOT NULL,
  answer TEXT NOT NULL,
  languageCode TEXT NOT NULL,
  questionId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (languageCode) REFERENCES languages(code) ON DELETE CASCADE,
  FOREIGN KEY (questionId) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE answers (
  id TEXT NOT NULL,
  answer TEXT NOT NULL,
  autoPointsAwarded NUMERIC
  pointsAwarded NUMERIC,
  teamId TEXT NOT NULL,
  questionInfoId TEXT NOT NULL,
  createdAt NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (teamId) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (questionInfoId) REFERENCES questionsInfo(id) ON DELETE CASCADE
);
